name: hm_cloud

description: HaiMa cloud plugin.
version: 0.1.7
homepage: https://github.com/Rambo0422/hm_cloud_flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: com.sayx.hm_cloud
        pluginClass: HmCloudPlugin
      ios:
        pluginClass: HmCloudPlugin